# Generated by Django 5.1.1 on 2024-09-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npjAirport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csit",
            name="mob",
            field=models.CharField(max_length=10),
        ),
    ]
